---
- hosts: k8s
  tasks:
  - name: install the latest version of yum-utils
    yum:
      name: yum-utils
      state: latest

  - name: add docker repo 
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: install the latest version of docker
    yum:
      name: docker-ce
      state: latest

  - name: install the latest version of docker cli 
    yum:
      name: docker-ce-cli
      state: latest

  - name: install containerd 
    yum:
      name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
      state: present
  
  - name: start docker service 
    systemd: state=started name=docker

  - name: enable docker service 
    systemd:
      name: docker
      enabled: yes
      masked: no