---
- hosts: master-node
  tasks:
  - name: adding kubernetes repository to YUM 
    yum_repository:
      name: kubernetes
      description: kubernetes
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes
      enabled: yes

  - name: install the latest version of kudeadm , kubectl and kubelet
    yum:
      name: 
        - kubeadm
        - kubelet
        - kubectl 
      state: latest

  - name: enable kubelet service 
    systemd:
      name: kubelet
      enabled: yes
      masked: no
 
  - name: start kubelet service 
    systemd: state=started name=kubelet

  - name: add ports to firewalld 
    firewalld:
      immediate: yes
      permanent: true
      state: enabled
      port: "{{item.port}}/{{item.protocol}}"
    with_items:
     - {port: "6443", protocol: "tcp" }
     - {port: "2379-2380", protocol: "tcp" }
     - {port: "10250", protocol: "tcp" }
     - {port: "10251", protocol: "tcp" }
     - {port: "10252", protocol: "tcp" }
     - {port: "10255", protocol: "tcp" }
# ports for weave net pod network
     - {port: "6783", protocol: "tcp" }
     - {port: "6783", protocol: "udp" }
     - {port: "6784", protocol: "udp" }

  - name: reload firewalld 
    command: firewall-cmd --reload


  - name: Updating IP Tables 
    shell:
      cmd: |
        cat <<EOF > /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        EOF
        sysctl --system

  - name: Disable SeLinux
    shell:
      cmd: |
        setenforce 0
        sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux

  - name: Disable SWAP
    shell:
      cmd: |
        sed -i '/swap/d' /etc/fstab
        swapoff -a

